; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Thu Jul 12 2018 20:54:00 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0